faktury/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('invoice.urls')),
    path('admin/', admin.site.urls),
]

invoice/urls.py
from django.urls import path

from . import views

app_name = 'invoice'
urlpatterns = [
	path('', views.index, name='index'),
	path('firma/', views.firmas_all, name='firmas_all'),
	path('zakaznici/', views.zakaznik_all, name='zakaznik_all'),
	path('logmein/', views.log_in, name='log_in'),
	path('faktury/', views.faktury_all, name='faktury_all'),
	path('detail/<int:faktura_id>/	', views.detail, name='detail'),
	path('detail/<int:faktura_id>/edit/', views.edit_detail, name='edit_detail'),
	path('firma/<int:firma_id>/', views.firma, name='firma'),
	path('zakaznik/<int:zakaznik_id>/', views.zakaznik, name='zakaznik'),
	path('kontakt/', views.kontakt, name='kontakt'),

]

invoice/models.py
from django.db import models
import uuid
from django.core.validators import RegexValidator
from django.db.models import Sum, F


# Create your models here.


class Login(models.Model):
    id = models.AutoField(primary_key=True)
    db_uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    user = models.CharField(blank=False, unique=True, max_length=50)
    email = models.EmailField(blank=False)
    password = models.CharField(blank=False, max_length=150)

    def __str__(self):
        return self.user


class Firma(models.Model):
    id = models.AutoField(primary_key=True)
    db_uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    creator = models.ForeignKey(Login, blank=False, on_delete=models.CASCADE,)
    nazov = models.CharField(blank=False, max_length=200)
    meno = models.CharField(blank=False, max_length=50)
    priezvisko = models.CharField(blank=False, max_length=50)
    ico = models.CharField(blank=False, max_length=50)
    dic = models.CharField(blank=False, max_length=50)
    banka = models.CharField(blank=False, max_length=100)
    alphanumeric = RegexValidator(r'^[0-9a-zA-Z]*$', 'Zadajte cislo vo formate IBAN')
    cislo_uctu = models.CharField(blank=False, max_length=24, validators=[alphanumeric])
    banky = (
        ('', 'vyberte'),
        ('SUBASKBX', 'Všeobecná úverová banka, a. s.'),
        ('GIBASKBX', 'Slovenská sporiteľňa, a. s.'),
        ('TATRSKBX', 'Tatra banka, a. s.'),
        ('BREXSKBX', 'MBANK – BRE Bank SA, pobočka zahraničnej banky mBank v SR'),
        ('UNCRSKBX', 'UniCredit Bank Czech Republic and Slovakia, a. s., pobočka zahr. banky'),
        ('CEKOSKBX', 'ČSOB – Československá obchodná banka, a.s.'),
    )
    cislo_swift = models.CharField(max_length=8, choices=banky, default='', blank=False)
    platca_DPH = models.CharField(choices=[("20", "ano"), ("0", "nie")], max_length=2)
    telefon = models.CharField(max_length=50)
    adresa_ulica = models.CharField(max_length=200)
    adresa_mesto = models.CharField(max_length=90)
    adresa_PSC = models.CharField(max_length=20)

    def __str__(self):
        return self.nazov


class Zakaznik(models.Model):
    id = models.AutoField(primary_key=True)
    db_uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(Login, blank=False, on_delete=models.CASCADE,)
    creator = models.ForeignKey(Firma, blank=False, on_delete=models.CASCADE,)
    nazov = models.CharField(blank=True, max_length=200)
    meno = models.CharField(blank=True, max_length=50)
    cislo = models.CharField(blank=True, max_length=50)
    priezvisko = models.CharField(blank=True, max_length=50)
    adresa_ulica = models.CharField(max_length=200)
    adresa_mesto = models.CharField(max_length=90)
    adresa_psc = models.CharField(max_length=20)
    ico = models.CharField(blank=False, max_length=50)
    dic = models.CharField(blank=False, max_length=50)
    icdph = models.CharField(blank=False, max_length=50)
    banka = models.CharField(blank=False, max_length=100)
    cislo_uctu = models.CharField(blank=False, max_length=100)
    email = models.EmailField(blank=False)
    telefon = models.CharField(max_length=50)

    def __str__(self):
        return self.nazov


class Faktura(models.Model):
    id = models.AutoField(primary_key=True)
    db_uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(Login, blank=False, on_delete=models.CASCADE,)
    creator = models.ForeignKey(Firma, blank=False, on_delete=models.CASCADE,)
    created_for = models.ForeignKey(Zakaznik, blank=False, on_delete=models.CASCADE,)
    cislo_faktury = models.CharField(blank=False, max_length=10)
    datum_vystavenia = models.DateField(blank=False)
    datum_splatnosti = models.DateField(blank=False)
    datum_dodania = models.DateField(blank=False)
    konstantny_symbol = models.CharField(blank=False, max_length=150)
    doprava = models.CharField(blank=True, max_length=150)
    uhradena = models.CharField(choices=[("1", "ano"), ("0", "nie")], max_length=1, default=0)
    komentar = models.TextField(max_length=3000)

    def __str__(self):
        return self.cislo_faktury


class Polozky(models.Model):
    id = models.AutoField(primary_key=True)
    db_uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(Login, blank=False, on_delete=models.CASCADE,)
    faktura = models.ForeignKey(Faktura, blank=False, on_delete=models.CASCADE,)
    dan = models.DecimalField(blank=False, max_digits=20, decimal_places=2)
    nazov = models.CharField(blank=False, max_length=300)
    mnozstvo = models.DecimalField(blank=False, max_digits=20, decimal_places=2)
    kod = models.CharField(blank=True, max_length=100)
    cena = models.DecimalField(blank=False, max_digits=20, decimal_places=2)

    def spolu(self):
        return self.mnozstvo * self.cena

    spocitaj = models.IntegerField(default=0, editable=False)

    def __str__(self):
        return self.nazov

invoice/forms.py
#python
from django import forms

from .models import Login

class LoginForm(forms.ModelForm):
	class Meta:
		model = Login
		fields = ('email','password')

invoice/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponse, HttpResponseRedirect
#from django.template import Context, loader, RequestContext
from django.contrib.auth.decorators import login_required
#from django.shortcuts import render_to_response, redirect
#from django.template.context_processors import csrf
from django.template.loader import render_to_string
from django.contrib.auth import authenticate, login, logout
#from decimal import Decimal

# Create your views here.
from .models import *
from .forms import LoginForm


def index(request):
    Fakturas_list = Faktura.objects.all()
    Login_list = Login.objects.all()
    sucet_list = Polozky.objects.all()#.aggregate(total=Sum(F('mnozstvo') * F('cena')))['total']
    return render(request, 'invoice/index.html',
                  {'Fakturas_list': Fakturas_list, 'Login_list': Login_list, 'form': LoginForm, 'sucet_list': sucet_list})

def kontakt(request):
    return render(request, 'invoice/kontakt.html')


####custom login - not in use

def log_in(request):
    if request.method == 'POST':
        form = LoginForm(request.POST or None)
        if form.is_valid():
            username = User.objects.get(email=form.cleaned_data['email'])
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    auth_login(request, user)
                    return render(request, 'invoice/index.html',
                                  {'Fakturas_list': Fakturas_list, 'Login_list': Login_list})
            else:
                form = LoginForm(request.POST or None)
            return HttpResponseRedirect('/?there_you_go')
    else:
        form = LoginForm(request.POST or None)
    return HttpResponseRedirect('/?no_login_requested')


@login_required(login_url='/logmein/')
def detail(request, faktura_id):
    faktura = get_object_or_404(Faktura, pk=faktura_id)
    polozky = Polozky.objects.filter(faktura=faktura_id)
    # zakaznik = Zakaznik.objects.filter(faktura=faktura.db_uuid)
    zakaznik = Zakaznik.objects.get(faktura=faktura.id)
    sucet = Polozky.objects.filter(faktura=faktura_id).aggregate(total=Sum(F('mnozstvo') * F('cena')))['total']
    t = 'invoice/details.html'
    c = {'faktura': faktura, 'polozky': polozky, 'zakaznik': zakaznik, 'sucet': sucet}
    return HttpResponse(render_to_string(t, c))


@login_required(login_url='/logmein/')
def firmas_all(request):
    Firmas_list = Firma.objects.all()
    t = 'invoice/firmas.html'
    c = {'Firmas_list': Firmas_list, }
    return HttpResponse(render_to_string(t, c))


@login_required(login_url='/logmein/')
def zakaznik_all(request):
    zakaznik_list = Zakaznik.objects.all()
    t = 'invoice/zakaznici.html'
    c = {'zakaznik_list': zakaznik_list, }
    return HttpResponse(render_to_string(t, c))


@login_required(login_url='/logmein/')
def faktury_all(request):
    Fakturas_list = Faktura.objects.all()
    t = 'invoice/faktury.html'
    c = {'Fakturas_list': Fakturas_list, }
    return HttpResponse(render_to_string(t, c))


@login_required(login_url='/logmein/')
def firma(request, firma_id):
    firma = get_object_or_404(Firma, pk=firma_id)
    zoznam = Faktura.objects.filter(creator=firma.id)
    t = 'invoice/firma.html'
    c = {'firma': firma, 'zoznam': zoznam}
    return HttpResponse(render_to_string(t, c))


@login_required(login_url='/logmein/')
def zakaznik(request, zakaznik_id):
    zakaznik = get_object_or_404(Zakaznik, pk=zakaznik_id)
    zoznam = Faktura.objects.filter(created_for=zakaznik.id)
    t = 'invoice/zakaznik.html'
    c = {'zakaznik': zakaznik, 'zoznam': zoznam}
    return HttpResponse(render_to_string(t, c))


@login_required(login_url='/logmein/')
def edit_detail(request, faktura_id):
    faktura = get_object_or_404(Faktura, pk=faktura_id)
    try:
        zmeny = faktura.cislo_faktury.get(pk=request.POST['komentar'])
    except(KeyError, Faktura.DoesNotExist):
        return render(request, 'invoice/details.html#letsedit', {
            'faktura': faktura, 'error_message': "Chyba, ne-existujuci/neaktualny zaznam",
        })
    else:
        zmeny.edit_details += 1
        zmeny.save()
    return HttpResponseRedirect(reverse('faktura:faktura', args=(faktura.id,)))

templates/invoice/details.html
<!DOCTYPE html>
<html>
<head>

    {% include "invoice/head.html" %}

    <style type="text/css">
.btn {float:right;}
#qrcode {padding-right:25px; float:right; z-index:1}
@media print
{
@page { margin: 0; }
    body {font-family:Arial}
    .breadcrumb{display:none;}
    h1 {padding-bottom:30px;color:gray; float:right; position:absolute: z-index:1}
    #qrcode {padding-right:25px; float:right; z-index:1; padding-top:-200px}
    .nav{display:none;}
    .btn{display:none;}
    .navbar-header {display:none;}
    .dodavatel {float:left; position:absolute: z-index:1;}
    .odbetratel {float:right; position:absolute: z-index:1; padding-right:190px}
    .qr-print {width:400px; }
}


    </style>
    <script>

function printMe(){
     $("#body").show();
    window.print();
};

    </script>
    <title>Faktura {{faktura.cislo_faktury}} - {{ faktura.creator.nazov }} - {{zakaznik.nazov}}</title>

</head>

<body>
{% include "invoice/nav.html" %}
{% load l10n %}
<div class="container-fluid">

    <ol class="breadcrumb">
        <li><a href="/">Domov</a></li>
        <li><a href="{% url 'invoice:faktury_all' %}">Faktury</a></li>
        <li class="active">Detail</li>
    </ol>
    <!--<button type="button" class="btn btn-danger"  OnClick=" location.href='/admin/' ">Admin</button> -->
    <button type="button" class="btn" title="Vytlacit fakturu c. {{faktura.cislo_faktury}} " onclick="printMe()"><i class="glyphicon glyphicon-print"></i></button>

    <h1>Faktura: {{faktura.cislo_faktury}}</h1>
    <div id="details">
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <div class="row">
            <div class="col-lg-6 dodavatel">
                <h3><b>Dodavatel:</b></h3>
                <h4>{{ faktura.creator.nazov }}</h4>
                <h4><b>ICO:</b> {{ faktura.creator.ico }}</h4>
                <h4><b>DIC:</b> {{ faktura.creator.dic }}</h4>
                <hr class="soften"/>
                <h4><b>Bankove udaje:</b></h4>
                <h4>{{ faktura.creator.banka }}</h4>
                <h4>IBAN: {{ faktura.creator.cislo_uctu }}</h4>
                <hr class="soften"/>
                <h4><b>Datum vystavenia:</b> {{faktura.datum_vystavenia}}</h4>
                <h4><b>Datum splatnosti:</b> {{faktura.datum_splatnosti}}</h4>


            </div>
            <div class="col-lg-6 odbetratel">
                <h3><b>Odbetratel:</b></h3>
                <p>{{zakaznik.nazov}}</p>
                <h4><b>Meno:</b></h4>
                <p>{{zakaznik.meno}} {{zakaznik.priezvisko}}</p>
                <p>{{zakaznik.adresa_ulica}} <br/> {{zakaznik.adresa_mesto}} <br/> {{zakaznik.adresa_psc}}</p>
            </div>

        </div>

            <div class="row">
                <div class="col-lg-6">
                <hr class="soften"/>
                <h5><b>Komentar:</b></h5>
                <p>{{faktura.komentar}}</p>
                <hr class="soften"/>
                </div>
                <div class="col-lg-6">
<img src="https://services.profit365.eu/API/QR/PayBySquare.png?IBAN={{ faktura.creator.cislo_uctu }}&BIC={{ faktura.creator.cislo_swift }}&Currency=EUR&Amount={{sucet|unlocalize}}&DueDate={{ faktura.datum_splatnosti|date:'Y-m-d'}}&VS={{faktura.cislo_faktury}}&CS=0000&SS=0000&Description={{zakaznik.meno}}+{{zakaznik.priezvisko}}&ID=&Size=256" class="qrcode" />
            </div>
            </div>


        {% if polozky %}

        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th colspan="5">Polozky</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th>Nazov</th>
                    <th>mnozstvo</th>
                    <th>cena (€)</th>
                    <th>Dan (%)</th>
                    <th>Spolu</th>
                </tr>
                {% for x in polozky.all %}
                <tr>
                    <td>{{ x.nazov }}</td>
                    <td>{{x.mnozstvo}}</td>
                    <td>{{x.cena}}</td>
                    <td>{{x.dan}}</td>
                    <td>{{ x.spolu|floatformat:2 }}</td>
                </tr>
                {% endfor %}
                <tr>
                    <td colspan="4" class="text-right bg-success"><b>Spolu total: </b></td>
                    <td class="bg-success"> {{ sucet|unlocalize }} €</td>
                </tr>
                </tbody>
            </table>
        </div>
        {% else %}
        <p>Ziaden zaznam.</p>
        {% endif %}


    </div>

</div>


</body>

</html>

templates/invoice/faktury.html
<!DOCTYPE html>
<html>
<head>

    {% include "invoice/head.html" %}

    <script>
$(document).ready(function(){
	$( "td.PAY:contains('0')").html("<span class='glyphicon glyphicon-remove' aria-hidden='true'></span> Neuhradene");
	$( "td.PAY:contains('1')").html("<span class='glyphicon glyphicon-check' aria-hidden='true'></span> Uhradene");
		});
    </script>
    <title>Faktury vseobecne</title>

</head>

<body>
{% include "invoice/nav.html" %}
<div class="container-fluid">


    <ol class="breadcrumb">
        <li><a href="/">Domov</a></li>
        <li class="active">Faktury</li>

    </ol>
    <!-- <button type="button" class="btn btn-danger"  OnClick=" location.href='/admin/' ">Admin</button> -->
    <h1>Zoznam mojich faktur</h1>


    {% if Fakturas_list %}
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th>Cislo</th>
                <th>Datum vystavenia</th>
                <th>Datum splatnosti</th>
                <th>Vytvoril</th>
                <th>Zakaznik</th>
                <th>Uhradena</th>
            </tr>
            </thead>
            <tbody>
            {% for b in Fakturas_list %}
            <tr>
                <td><a href="{% url 'invoice:detail' b.id %}">{{ b.cislo_faktury }}</a></td>
                <td>{{b.datum_vystavenia}}</td>
                <td>{{b.datum_splatnosti}}</td>
                <td>{{b.creator }}</td>
                <td>{{b.created_for.nazov}}</td>
                <td class="PAY">{{b.uhradena}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <p>Ziadne zaznamy.</p>
    {% endif %}
</div>
</body>

</html>

templates/invoice/firma.html
<!DOCTYPE html>
<html>
<head>
    {% include "invoice/head.html" %}
    <title>Faktura {{firma}}</title>

</head>

<body>
{% include "invoice/nav.html" %}
<div class="container-fluid">

    <ol class="breadcrumb">
        <li><a href="/">Domov</a></li>
        <li><a href="{% url 'invoice:firmas_all' %}">Firmy</a></li>
        <li class="active">Firma</li>

    </ol>
    <!--<button type="button" class="btn btn-danger"  OnClick=" location.href='/admin/' ">Admin</button> -->
    <h1>Detail Firmy: {{firma}}</h1>
    <p>
        Nazov: {{firma.nazov}} <br/>
        Meno: {{firma.meno}}, {{firma.priezvisko}}<br/>
        ico: {{firma.ico}}<br/>
        dic: {{firma.dic}}<br/>
        bankove udaje: {{firma.cislo_uctu}}, {{firma.banka}}
    </p>
    {% if zoznam %}
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th colspan="3">Faktury</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th>cislo</th>
                <th>datum</th>
                <th>datum splatnosti</th>
            </tr>
            {% for x in zoznam.all %}
            <tr>
                <td><a href="{% url 'invoice:detail' x.id %}">{{x.cislo_faktury}}</a></td>
                <td>{{x.datum_vystavenia}}</td>
                <td>{{x.datum_splatnosti}}</td>
            </tr>
            {% endfor %}
            {% else %}
            <p>Ziaden zaznam.</p>
            {% endif %}
            </tbody>
        </table>
    </div>

</div>
</body>

</html>

templates/invoice/firmas.html
<!DOCTYPE html>
<html>
<head>

    {% include "invoice/head.html" %}
    <title>Faktury zakaznika</title>
    <script>
$(document).ready(function(){
	$( "td.DPH:contains('platiDPH')").html("<span class='glyphicon glyphicon-euro' aria-hidden='true'></span> Plati DPH");
	$( "td.DPH:contains('neplatcaDPH')").html("<span class='glyphicon glyphicon-remove' aria-hidden='true'></span> Neplati DPH");
		});


    </script>
</head>

<body>
{% include "invoice/nav.html" %}
<div class="container-fluid">


    <ol class="breadcrumb">
        <li><a href="/">Domov</a></li>
        <li class="active">Firmy</li>
    </ol>
    <!-- <button type="button" class="btn btn-danger"  OnClick=" location.href='/admin/' ">Admin</button> -->
    <h1>Zoznam mojich firiem</h1>

    {% if Firmas_list %}
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th>Nazov</th>
                <th>ICO</th>
                <th>DIC</th>
                <th>Telefon</th>
                <th>Platca DPH</th>
            </tr>
            </thead>
            <tbody>
            {% for b in Firmas_list %}
            <tr>
                <td><a href="/firma/{{ b.id }}">{{ b.nazov }}</a></td>
                <td>{{b.ico}}</td>
                <td>{{b.dic}}</td>
                <td>{{b.telefon}}</td>
                <td class="DPH">{{ b.platca_DPH }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <p>Ziadne zaznamy.</p>
    {% endif %}
</div>
</body>

</html>

templates/invoice/gmaps.html
<!-- Google maps -->
<script>
function myMap() {
var mapProp= {
    center:new google.maps.LatLng(51.508742,-0.120850),
    zoom:5,
};
var map=new google.maps.Map(document.getElementById("gmaps"),mapProp);
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBaQdcjM_llWMpz-qW5ptDpl4sJQpbEFg4&callback=myMap"></script>

templates/invoice/index.html
<!DOCTYPE html>
<html lang="sk">
<head>

    {% include "invoice/head.html" %}

    <title>Faktury zakaznika</title>

</head>

<body>
{% include "invoice/nav.html" %}
<div class="container-fluid">


    <h1>Faktury online</h1>

    <h3> Jednoducha online faktracia</h3>
    {% if user.is_authenticated %}
    <p>Vitajte "{{ user.username }}" !!!</p>

    <h3>Zoznam vystavenych faktur:</h3>
    {% if Fakturas_list %}

    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th>Cislo</th>
                <th>Datum vystavenia</th>
                <th>Datum splatnosti</th>
                <th>Vytvoril</th>
            </tr>
            </thead>
            <tbody>
            {% for b in Fakturas_list %}
            <tr>
                <td><a href="{% url 'invoice:detail' b.id %}">{{ b.cislo_faktury }}</a></td>
                <td>{{ b.datum_vystavenia }}</td>
                <td>{{ b.datum_splatnosti }}</td>
                <td>{{ b.owner.user }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
<div id="chartContainer"></div>
    {% else %}
    <p>Ziaden zaznam.</p>

    {% endif %}

    {% else %}


    <div id="login" class="center_div">
        <p>Prihlaste sa:</p>
        <form name="LoginForm" action="/admin/login/?next=/" method="post" class="form-horizontal">
            <div class="form-group">
                {% csrf_token %}
                <label for="username" class="col-sm-2 control-label">Meno</label>
                <div class="col-sm-10"><input type="text" class="form-control" required name="username" id="username"
                                              placeholder="meno uzivatela"/></div>
                <label for="password" class="col-sm-2 control-label">Heslo</label>
                <div class="col-sm-10"><input type="password" class="form-control" required name="password"
                                              id="password" placeholder="heslo"/></div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary btn-xs">Prihlasit</button>
                </div>
            </div>
        </form>
    </div>

    {% endif %}

</div>



</body>

</html>

templates/invoice/kontakt.html
<!DOCTYPE html>
<html lang="sk">
<head>

    {% include "invoice/head.html" %}


    <title>Faktury zakaznika</title>

</head>

<body>
{% include "invoice/nav.html" %}
<div class="container-fluid">


    <h1>Faktury online</h1>
<div class="row">
                <div class="col-lg-6">
    <p> Kontaktne udaje</p>
    <p><b>My Company s.r.o</b></p>
    <p>Adresa 007/1945, <br />Ulica, <br />Mesto 007 01</p>
    <hr class="soften"/>
                    <p><i class="glyphicon glyphicon-envelope"></i> <a href="mailto:haha@notthateasy.com">info@minirobota.sk</a></p>
    <p><i class="glyphicon glyphicon-phone"></i> +421 2 007 007</p>
    <p><i class="glyphicon glyphicon-phone-alt"></i> +421 949 007 007 </p>
                </div>
         <div class="col-lg-6">
<p><i class="glyphicon glyphicon-map-marker"></i> Location on a Map:</p>
 <iframe
  width="400"
  height="300"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDkBJNoSBweFsDT3X0Xwrgc20iwUWaLgoI
    &q=Space+Needle,Seattle+WA" allowfullscreen>
</iframe>
</div>



</body>

</html>

templates/invoice/zakaznik.html
<!DOCTYPE html>
<html>
<head>
    {% include "invoice/head.html" %}
    <title>Detail zakaznika: {{zakaznik.nazov}}</title>

</head>

<body>
{% include "invoice/nav.html" %}
<div class="container-fluid">

    <ol class="breadcrumb">
        <li><a href="/">Domov</a></li>
        <li><a href="{% url 'invoice:zakaznik_all' %}">Zakaznici</a></li>
        <li class="active">Zakaznik</li>

    </ol>
    <!--<button type="button" class="btn btn-danger"  OnClick=" location.href='/admin/' ">Admin</button> -->
    <h1>Detail: {{zakaznik.nazov}}</h1>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    {% if zoznam %}
    <p>
        Nazov: {{ zakaznik.meno }}, {{ zakaznik.priezvisko }}<br/>
        Adresa: {{zakaznik.adresa_ulica}}, {{ zakaznik.adresa_mesto }}, {{ zakaznik.adresa_psc }}<br/>
        c. uctu: {{zakaznik.cislo_uctu}}<br/>
        email: {{zakaznik.email}}
    </p>
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th colspan="3">Faktury</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th>cislo</th>
                <th>datum</th>
                <th>datum splatnosti</th>
            </tr>
            {% for x in zoznam.all %}
            <tr>
                <td><a href="{% url 'invoice:detail' x.id %}">{{x.cislo_faktury}}</a></td>
                <td>{{x.datum_vystavenia}}</td>
                <td>{{x.datum_splatnosti}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <p>Ziaden zaznam.</p>
    {% endif %}
</div>
</body>

</html>